services:
  frontend:
    container_name: time-capsule-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - time-capsule
    environment:
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-secret-key-here
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
    
  backend:
    container_name: time-capsule-backend
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./backend:/var/www/html
    environment:
      WWWUSER: "${WWWUSER}"
      XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
      XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
    depends_on:
      - db
    networks:
      - time-capsule
    
  nginx:
    container_name: time-capsule-nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - time-capsule
    
  db:
    container_name: time-capsule-mysql
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: time_capsule
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - time-capsule
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s

  phpmyadmin:
    container_name: time-capsule-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    platform: linux/amd64
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=user
      - PMA_PASSWORD=password
      - UPLOAD_LIMIT=300M
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - time-capsule

networks:
  time-capsule:
    driver: bridge

volumes:
  mysql_data:
    driver: local